create table students
(
    id       integer generated by default as identity
        constraint students_pk
            primary key,
    name     varchar not null,
    gender   varchar not null,
    email    varchar not null,
    parent   varchar,
    location varchar
);

alter table students
    owner to postgres;

create table voters
(
    voter_id      integer generated by default as identity
        constraint voters_pk
            primary key,
    voter_kh_name varchar not null,
    date_of_birth date
);

alter table voters
    owner to postgres;

create table parties
(
    party_id  integer generated by default as identity
        constraint parties_pk
            primary key,
    part_name varchar
);

alter table parties
    owner to postgres;

create table votes
(
    vote_id         integer generated by default as identity
        constraint votes_pk
            primary key,
    vote_decription varchar not null,
    vote_date       date    not null,
    voter_id        integer not null
        constraint votes_voters_voter_id_fk
            references voters,
    party_id        integer not null
        constraint votes_parties_party_id_fk
            references parties
);

alter table votes
    owner to postgres;

create table users
(
    name varchar
);

alter table users
    owner to postgres;

